[project]
name = "ecommerce-trae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "flask>=3.1.1",
    "jinja2>=3.1.6",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
